version: "3.8"

networks:
  app-network:

services:
  backend:
    container_name: backend
    depends_on:
      - postgres
    build: ./backend
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped
  frontend:
    container_name: frontend
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "5252:5252"
    networks:
      - app-network
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:16.3
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network